/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jul 04 14:12:26 GMT 2018
 */

package com.dev.property.domain.services;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

@EvoSuiteClassExclude
public class FileSystemUploadService_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  protected static ExecutorService executor; 

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.dev.property.domain.services.FileSystemUploadService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    executor = Executors.newCachedThreadPool(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    executor.shutdownNow(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "/home/kyle/Desktop/Dev/property"); 
    java.lang.System.setProperty("user.home", "/home/kyle"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "kyle"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(FileSystemUploadService_ESTest_scaffolding.class.getClassLoader() ,
      "org.springframework.core.io.UrlResource",
      "com.dev.property.domain.services.FileSystemUploadService",
      "org.springframework.boot.context.properties.ConfigurationProperties",
      "org.apache.commons.fileupload.util.mime.MimeUtility",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "com.dev.property.domain.interfaces.UploadService",
      "org.springframework.stereotype.Service",
      "com.dev.property.upload.UploadFileNotFoundException",
      "org.apache.commons.fileupload.util.Streams",
      "com.dev.property.upload.UploadProperties",
      "org.springframework.stereotype.Indexed",
      "org.springframework.core.NestedExceptionUtils",
      "org.springframework.core.io.Resource",
      "org.springframework.util.FileSystemUtils$1",
      "org.apache.commons.fileupload.InvalidFileNameException",
      "org.apache.commons.io.input.ClosedInputStream",
      "org.apache.commons.fileupload.FileItem",
      "org.apache.commons.io.output.DeferredFileOutputStream",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.springframework.util.MultiValueMap",
      "org.springframework.core.NestedIOException",
      "org.apache.commons.fileupload.FileItemHeaders",
      "org.apache.commons.fileupload.util.FileItemHeadersImpl",
      "org.apache.commons.fileupload.util.mime.ParseException",
      "org.springframework.util.FileSystemUtils",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.util.ResourceUtils",
      "org.springframework.stereotype.Component",
      "org.apache.commons.fileupload.disk.DiskFileItem",
      "org.apache.commons.fileupload.FileItemHeadersSupport",
      "com.dev.property.upload.UploadException",
      "org.springframework.util.CollectionUtils",
      "org.springframework.core.io.InputStreamSource",
      "org.springframework.web.multipart.commons.CommonsMultipartFile",
      "org.apache.commons.fileupload.ParameterParser",
      "org.springframework.web.multipart.MultipartFile",
      "org.apache.commons.fileupload.FileUploadException",
      "org.apache.commons.io.output.ThresholdingOutputStream",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(FileSystemUploadService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.dev.property.domain.services.FileSystemUploadService",
      "com.dev.property.upload.UploadProperties",
      "org.springframework.core.io.AbstractResource",
      "org.springframework.core.io.AbstractFileResolvingResource",
      "org.springframework.core.io.UrlResource",
      "org.springframework.util.Assert",
      "org.springframework.util.StringUtils",
      "org.springframework.util.CollectionUtils",
      "org.springframework.util.ResourceUtils",
      "org.springframework.util.FileSystemUtils",
      "com.dev.property.upload.UploadException",
      "com.dev.property.upload.UploadFileNotFoundException",
      "org.springframework.util.FileSystemUtils$1",
      "org.apache.commons.fileupload.disk.DiskFileItem",
      "org.springframework.web.multipart.commons.CommonsMultipartFile",
      "org.apache.commons.fileupload.util.Streams",
      "org.apache.commons.fileupload.ParameterParser",
      "org.apache.commons.io.output.ThresholdingOutputStream",
      "org.apache.commons.io.output.DeferredFileOutputStream",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.fileupload.util.FileItemHeadersImpl",
      "org.apache.commons.fileupload.util.mime.MimeUtility"
    );
  }
}
