/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Wed Jul 04 14:15:24 GMT 2018
 */

package com.dev.property.domain.services;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class PropertyParseService_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.dev.property.domain.services.PropertyParseService"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "GB"); 
    java.lang.System.setProperty("user.dir", "/home/kyle/Desktop/Dev/property"); 
    java.lang.System.setProperty("user.home", "/home/kyle"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "kyle"); 
    java.lang.System.setProperty("user.timezone", "Europe/London"); 
    java.lang.System.setProperty("log4j.configuration", "SUT.log4j.properties"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(PropertyParseService_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.log4j.or.ObjectRenderer",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.commons.fileupload.util.mime.MimeUtility",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.Logger",
      "com.dev.property.model.Property",
      "org.apache.log4j.Level",
      "org.apache.commons.fileupload.util.Streams",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.Category",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.fileupload.util.FileItemHeadersImpl",
      "org.apache.commons.fileupload.util.mime.ParseException",
      "org.apache.log4j.spi.RepositorySelector",
      "org.apache.log4j.spi.Filter",
      "org.apache.log4j.spi.LoggerFactory",
      "org.apache.log4j.CategoryKey",
      "com.dev.property.domain.interfaces.ParseService",
      "org.apache.log4j.spi.Configurator",
      "org.springframework.core.io.InputStreamSource",
      "com.dev.property.model.Property$PropertyType",
      "org.apache.log4j.Layout",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.spi.LocationInfo",
      "org.apache.log4j.spi.ThrowableRendererSupport",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.ProvisionNode",
      "org.apache.log4j.spi.ThrowableRenderer",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.Appender",
      "org.springframework.stereotype.Service",
      "org.springframework.stereotype.Indexed",
      "org.apache.commons.fileupload.InvalidFileNameException",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.spi.OptionHandler",
      "org.apache.log4j.spi.HierarchyEventListener",
      "org.apache.commons.io.input.ClosedInputStream",
      "org.apache.log4j.spi.RootLogger",
      "com.dev.property.domain.services.PropertyParseService",
      "org.apache.commons.fileupload.FileItem",
      "org.apache.commons.io.output.DeferredFileOutputStream",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.apache.log4j.spi.ErrorHandler",
      "org.apache.log4j.spi.LoggingEvent",
      "org.apache.commons.fileupload.FileItemHeaders",
      "org.apache.log4j.spi.RendererSupport",
      "org.apache.log4j.spi.ThrowableInformation",
      "org.springframework.stereotype.Component",
      "org.apache.commons.fileupload.disk.DiskFileItem",
      "org.apache.log4j.Priority",
      "org.apache.commons.fileupload.FileItemHeadersSupport",
      "org.springframework.web.multipart.commons.CommonsMultipartFile",
      "org.apache.commons.fileupload.ParameterParser",
      "org.springframework.web.multipart.MultipartFile",
      "org.apache.log4j.spi.LoggerRepository",
      "org.apache.commons.fileupload.FileUploadException",
      "org.apache.log4j.LogManager",
      "org.apache.commons.io.output.ThresholdingOutputStream",
      "org.apache.log4j.helpers.OptionConverter"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(PropertyParseService_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.spi.RootLogger",
      "org.apache.log4j.Priority",
      "org.apache.log4j.Level",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.ProvisionNode",
      "com.dev.property.domain.services.PropertyParseService",
      "com.dev.property.model.Property$PropertyType",
      "com.dev.property.model.Property",
      "org.apache.commons.fileupload.disk.DiskFileItem",
      "org.springframework.web.multipart.commons.CommonsMultipartFile",
      "org.apache.commons.fileupload.ParameterParser",
      "org.apache.commons.fileupload.util.Streams",
      "org.apache.commons.io.output.ThresholdingOutputStream",
      "org.apache.commons.io.output.DeferredFileOutputStream",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.fileupload.util.FileItemHeadersImpl",
      "org.apache.commons.fileupload.util.mime.MimeUtility"
    );
  }
}
