/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 04 13:13:16 GMT 2018
 */

package com.dev.property;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.dev.property.PropertyDataApplication;
import com.dev.property.domain.interfaces.UploadService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.springframework.boot.CommandLineRunner;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PropertyDataApplication_ESTest extends PropertyDataApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        PropertyDataApplication.main(stringArray0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class org.springframework.boot.SpringApplication
         //
         verifyException("com.dev.property.PropertyDataApplication", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PropertyDataApplication propertyDataApplication0 = new PropertyDataApplication();
      CommandLineRunner commandLineRunner0 = propertyDataApplication0.init((UploadService) null);
      assertNotNull(commandLineRunner0);
  }
}
