/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 04 13:54:39 GMT 2018
 */

package com.dev.property.upload;

import org.junit.Test;
import static org.junit.Assert.*;
import com.dev.property.upload.UploadProperties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UploadProperties_ESTest extends UploadProperties_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UploadProperties uploadProperties0 = new UploadProperties();
      uploadProperties0.setLocation((String) null);
      String string0 = uploadProperties0.getLocation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UploadProperties uploadProperties0 = new UploadProperties();
      uploadProperties0.setLocation("");
      String string0 = uploadProperties0.getLocation();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UploadProperties uploadProperties0 = new UploadProperties();
      String string0 = uploadProperties0.getLocation();
      assertEquals("upload-dir", string0);
  }
}
