/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 04 13:54:10 GMT 2018
 */

package com.dev.property.upload;

import org.junit.Test;
import static org.junit.Assert.*;
import com.dev.property.upload.UploadException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UploadException_ESTest extends UploadException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UploadException uploadException0 = new UploadException("");
      MockThrowable mockThrowable0 = new MockThrowable(uploadException0);
      UploadException uploadException1 = new UploadException("", mockThrowable0);
      assertFalse(uploadException1.equals((Object)uploadException0));
  }
}
