/*
 * This file was automatically generated by EvoSuite
 * Wed Jul 04 13:54:24 GMT 2018
 */

package com.dev.property.upload;

import org.junit.Test;
import static org.junit.Assert.*;
import com.dev.property.upload.UploadFileNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UploadFileNotFoundException_ESTest extends UploadFileNotFoundException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UploadFileNotFoundException uploadFileNotFoundException0 = new UploadFileNotFoundException("J#aIHrDR3");
      UploadFileNotFoundException uploadFileNotFoundException1 = new UploadFileNotFoundException("Path must not be null/empty!", uploadFileNotFoundException0);
      assertFalse(uploadFileNotFoundException1.equals((Object)uploadFileNotFoundException0));
  }
}
